# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
